Nucleos = ["A","T","C","G"]

def vSeq(seq):
    nseq =seq.upper()
    for i in nseq:
        if i not in Nucleos:
            return False
    return nseq


def countDNA(seq):
    dnaString = {"A":0, "C": 0, "G": 0, "T":0}
    for i in seq:
        dnaString[i] +=1
    return dnaString

DNA = "AAATTGTTTCAAGATGGGTCGGTTGATATCGAGACGGAACGATCGGGATTGCAATACGCGGCATAGAGACCTAATGCGTGCCCTCATCATGATACTTCGGCTCGTGTCTAGGGCCTTAGGGGAGCAGATCAGGGTCGTTTCAAACATGCTTTATAGCCTAGGACGTTCCTGGCTATCTTTTACAGCAACTGGCTTCACTTGTAACGTGCACACAATTGCAACCCCATTGGCCCAGAGCGCTCTTCACGTACAACCCCTTAGGTATAATCACACCACTCAACCGTCTCGCAGAGATGGCCCAATTCTGCAACTGGTCATGCGTCCGTCTATCTTGGATACGTGGGTTTAGCAACCTGGTATTCCCTATGCTCACCTCTTCGCACGAAGACATGGAGACAAGATAAGGAGATGCGGCGGGAGCATTTCCAACCTAGACTGAACCGTACGTAGGAGGAGGCTTAACAGCGCGATGAACCAACACGGGAGTTCCCAACCAGGCTGGACACGATCGGCTCCACGCTCCACGGGTACACCGATTCCGAGATACATCGCAAAATACCAATGATGTTGAGCTCTGTACTGCTTATGGCTACAGCCTGCTAGAGGCTATCATTTAGCTTGAACGGTGTATCCCCATAGTTGAGAAGTCCCAAGGATTTGGGTTAGATCGACCAAGTCAGAGTTGTGCAATAGGTAGTGAGGACACTAGTACACTGAACAGCATATGCGACTCCGAGTTCAGCTCTAACAACTCAGCAGGTCAACTCCTCATAGGGAGACCGTATTTAACGTCTGGTCCCAGAGGACACTACCGGGAGGTAAAGATTCATAATTATGATTCTGTCTCAACTGGAACCGCTCTTAAAGGTAGAATACCGAATTAGGCCCAACTGTTCACGCCACTCTCTCAAGCGCGCAGTCACGTAGCGAATGTGCGCGGTTGTTGTGGATTGGTGTACGACGTCGTCGTAACTTCCCACTCAGCGCCATTTGCATTG"
result = countDNA(DNA)
print(' '.join([str(val)for key, val in result.items()]))